cat <<EOF > docker-compose.yml
version: '3.8'

services:
  automation-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: python3 app.py
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - automation-app
    restart: always
EOF
