version: "3.3"
services:
  automation-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - chrome-container

  chrome-container:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
